# Generated by Django 4.2.2 on 2023-06-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='foods',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='name',
        ),
        migrations.AddField(
            model_name='meal',
            name='breakfast',
            field=models.ManyToManyField(related_name='breakfast', to='main_app.food'),
        ),
        migrations.AddField(
            model_name='meal',
            name='dinner',
            field=models.ManyToManyField(related_name='dinner', to='main_app.food'),
        ),
        migrations.AddField(
            model_name='meal',
            name='lunch',
            field=models.ManyToManyField(related_name='lunch', to='main_app.food'),
        ),
    ]
