# Generated by Django 4.2.2 on 2023-06-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_meal_foods_remove_meal_name_meal_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='breakfast',
            field=models.ManyToManyField(blank=True, related_name='breakfast', to='main_app.food'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='dinner',
            field=models.ManyToManyField(blank=True, related_name='dinner', to='main_app.food'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='lunch',
            field=models.ManyToManyField(blank=True, related_name='lunch', to='main_app.food'),
        ),
    ]
