# Generated by Django 4.2.2 on 2023-06-21 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_meal_calories_meal_carbs_meal_fat_meal_protein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='protein',
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=100)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.meal')),
            ],
        ),
    ]
