# Generated by Django 4.2.2 on 2023-06-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_meal_calories_remove_meal_carbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='protein',
            field=models.IntegerField(default=0),
        ),
    ]
