# Generated by Django 4.2.2 on 2023-06-21 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_mealfood_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealfood',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
